;Game constants
;==============

SCREEN_ADDRESS = $4000

SCREEN_WIDTH = 256
SCREEN_HEIGHT = 128

MAP_WIDTH = 40
MAP_HEIGHT = 20

LEGEND_WIDTH = 96
LEGEND_HEIGHT = 128
LEGEND_LEFT = 160
LEGEND_TOP = 0

FRAME_WIDTH = 5
FRAME_HEIGHT = 4

DIRECTION_NONE = 0
DIRECTION_UP = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3
DIRECTION_RIGHT = 4

OUTPUT_GAME = 0
OUTPUT_CHARACTER = 1
OUTPUT_SKILLS = 2
OUTPUT_RESOURCES = 3
OUTPUT_GAME_OVER = 4

MAP_LAVA_COUNT = 20
MAP_WALL_COUNT = 60
MAP_LAVA_SIZE = 5
MAP_WALL_SIZE = 5
MAP_BLANK = 0
MAP_BLANK_90 = 1
MAP_BLANK_180 = 2
MAP_BLANK_270 = 3
MAP_ROCK = 4
MAP_LAVA = 5
MAP_EXIT = 6

HERO_START_X = 1
HERO_START_Y = 1

SLOT_COUNT = 5

MONSTER_HP  =  30

SKILL_COUNT = 15
SKILL_BATTERY_SAVER = 0
SKILL_BOUNTY_HUNTER = 1
SKILL_FAST_DIGGER = 2
SKILL_LUCKY_DRILLER = 3
SKILL_MASTER_MINER = 4
SKILL_LUCKY_CRIT = 5
SKILL_CRIT_LORD = 6
SKILL_EXPERIENCED = 7
SKILL_INSTAKILL = 8
SKILL_GHOST = 9
SKILL_FREE_LUNCH = 10
SKILL_WISE_REWARDS = 11
SKILL_BIG_DISCOUNT = 12
SKILL_ONLY_THE_BEST = 13
SKILL_CRYSTALSMITH = 14

COLOR_BLACK = 0
COLOR_WHITE = 63
COLOR_GREEN = 12
COLOR_RED = 3
COLOR_DARK_RED = 2
COLOR_BLUE = 48
COLOR_DARK_BLUE = 32
COLOR_DARK_GREEN = 8
COLOR_PURPLE = 50
COLOR_DARK_PURPLE = 33
COLOR_ORANGE = 11
COLOR_DARK_ORANGE = 6
COLOR_YELLOW = 15
COLOR_DARK_YELLOW = 10
COLOR_GRAY_1 = 21
COLOR_GRAY_2 = 42
COLOR_TRANSPARENT = 64

COLOR_LEGEND_BG = 21
COLOR_ROCK = 33
COLOR_DIRT = 59
COLOR_LAVA = 11
COLOR_CRYSTAL_RED1 = 23
COLOR_CRYSTAL_RED2 = 43
COLOR_CRYSTAL_YELLOW1 = 31
COLOR_CRYSTAL_YELLOW2 = 47
COLOR_CRYSTAL_BLUE1 = 53
COLOR_CRYSTAL_BLUE2 = 58
COLOR_EXIT = 53
COLOR_MONSTER = 1

COLOR_HP = 3
COLOR_BATT = 48
COLOR_DMG = 1
COLOR_CRIT = 1
COLOR_MINE = 23
COLOR_DRILL = 50
COLOR_LAVA_RES = 11

COLOR_MENU_CHAR = 8
COLOR_MENU_SKILLS = 32
COLOR_MENU_RESOURCES = 2
COLOR_MENU_BORDER = 42

INVENTORY_COUNT = 30
TEXT_LINE_HEIGHT = 8
TEXT_CHAR_WIDTH = 6
TEXT_SPACING_Y = 10
MONSTER_COUNT = 40
CRYSTAL_COUNT = 40
BAR_WIDTH = 80
BAR_HEIGHT = 6
LEGEND_MAZE_TOP = 84
LEGEND_MAZE_LEFT = 8
LEGEND_MAZE_MONSTER_COLOR = 3
LEGEND_MAZE_MINERAL_COLOR = 15
LEGEND_BOX_WIDTH = 10
LEGEND_BOX_HEIGHT = 8
LEGEND_STATS_LEFT = 8
LEGEND_HP_TOP = 4
LEGEND_HP_BAR_TOP = 13
LEGEND_BATT_TOP = 24
LEGEND_BATT_BAR_TOP = 33
LEGEND_EXP_TOP = 44
LEGEND_EXP_BAR_TOP = 53
LEGEND_TARGET_TOP = 64
LEGEND_TARGET_BAR_TOP = 73
DRAWITEM_RES_LEFT = 2
DRAWITEM_RES_TOP = 2
DRAWITEM_ITEM_LEFT = 18
DRAWITEM_ITEM_TOP = 4
DRAWITEM_STAT_TOP = 15
DRAWITEM_STAT_HEIGHT = 10
MENU_CHAR_LEFT = 9
MENU_TITLE_TOP = 9
MENU_SKILL_LEFT = 76
MENU_RES_LEFT = 124
MENU_BG_LEFT = 9
MENU_BG_TOP = 17
MENU_BG_WIDTH = 238
MENU_BG_HEIGHT = 102
MENU_CHAR_ROBOT_LEFT = 27
MENU_CHAR_ROBOT_TOP = 21
MENU_CHAR_STAT_LEFT = 13
MENU_CHAR_HP_TOP = 56
MENU_CHAR_BATT_TOP = 65
MENU_CHAR_DMG_TOP = 74
MENU_CHAR_CRIT_TOP = 83
MENU_CHAR_MINE_TOP = 92
MENU_CHAR_DRILL_TOP = 101
MENU_CHAR_LAVA_TOP = 110
MENU_CHAR_BOX_COLOR = 4
MENU_CHAR_BOX_LEFT = 80
MENU_CHAR_BOX1_TOP = 22
MENU_CHAR_BOX2_TOP = 70
MENU_CHAR_BOX_WIDTH = 80
MENU_CHAR_BOX_HEIGHT = 45
MENU_CHAR_BOX_TITLE_OFFSET_X = 18
MENU_CHAR_BOX_TITLE_OFFSET_Y = 4
MENU_CHAR_BOX_STAT_OFFSET_X = 18
MENU_CHAR_BOX_STAT_OFFSET_Y = 15
MENU_CHAR_GRID_LEFT = 164
MENU_CHAR_GRID_TOP = 20
MENU_CHAR_GRID_LINE_TOP = 116
MENU_CHAR_GRID_LINE_WIDTH = 80
MENU_CHAR_GRID_LINE_LEFT = 244
MENU_CHAR_GRID_LINE_HEIGHT = 97
MENU_CHAR_BOX_X_COUNT = 5
MENU_CHAR_BOX_Y_COUNT = 6
MENU_SKILL_POINTS_LEFT = 11
MENU_SKILL_POINTS_TOP = 20
MENU_SKILL_BOX1_COLOR = 46
MENU_SKILL_BOX2_COLOR = 58
MENU_SKILL_BOX3_COLOR = 43
MENU_SKILL_BOX_LEFT = 9
MENU_SKILL_BOX1_TOP = 29
MENU_SKILL_BOX2_TOP = 59
MENU_SKILL_BOX3_TOP = 89
MENU_SKILL_BOX_WIDTH = 140
MENU_SKILL_BOX_HEIGHT = 30
MENU_SKILL_X_SPACING = 28
MENU_SKILL_Y_SPACING = 30
MENU_SKILL_SKILL_LEFT = 11
MENU_SKILL_SKILL_TOP = 32
MENU_SKILL_DBOX_COLOR = 16
MENU_SKILL_DBOX_WIDTH = 92
MENU_SKILL_DBOX_HEIGHT = 87
MENU_SKILL_DBOX_LEFT = 152
MENU_SKILL_DBOX_TOP = 29
MENU_SKILL_DBOX_TEXT_LEFT = 154
MENU_SKILL_DBOX_TEXT_TOP = 43
MENU_SKILL_DBOX_TITLE_TOP = 31
MENU_SKILL_UPGRADE_LEFT = 154
MENU_SKILL_UPGRADE_TOP = 106
MENU_RES_BLOCK_HEIGHT = 19
MENU_RES_BLOCK_WIDTH = 23
MENU_RES_BLOCK_LEFT = 11
MENU_RES_BLOCK_TOP = 19
MENU_RES_BLOCK_TOTAL_HEIGHT = 97
MENU_RES_ITEM_LEFT = 14
MENU_RES_ITEM_TOP = 21
MENU_RES_BOX_WIDTH = 92
MENU_RES_BOX_HEIGHT = 87
MENU_RES_BOX_COLOR = 1
MENU_RES_BOX_LEFT = 152
MENU_RES_BOX_TOP = 29
MENU_RES_MONEY_LEFT = 152
MENU_RES_MONEY_TOP = 19
MENU_RES_MONEY_WIDTH = 92
MENU_RES_MONEY_HEIGHT = 10
MENU_RES_MONEY_VAL_TOP = 21
MENU_RES_MONEY_RED_LEFT = 171
MENU_RES_MONEY_BLUE_LEFT = 195
MENU_RES_MONEY_YELLOW_LEFT = 219
MENU_RES_COST_LEFT = 154
MENU_RES_COST_TOP = 107

MENU_RES_HP_COLOR1 = 1
MENU_RES_HP_COLOR2 = 23
MENU_RES_BATT_COLOR1 = 16
MENU_RES_BATT_COLOR2 = 53
MENU_RES_EXP_COLOR1 = 5
MENU_RES_EXP_COLOR2 = 31

MENU_BORDER_SIZE = 8

HERO_HP_BASE = 2
HERO_BATT_BASE = 3
HERO_MINE_BASE = 8
HERO_DRILL_BASE = 12
HERO_LAVA_RES_BASE = 0
HERO_BATT_RATE_BASE = 1
HERO_CRIT_BASE = 5
HERO_HP_RECHARGE_BASE = 0
HERO_LAVA_DMG_BASE = 4
HERO_ATTACK_COST_BASE = 4
HERO_MINE_COST_BASE = 2
HERO_DRILL_COST_BASE = 2
HERO_EXP_MAX_BASE = 40
HERO_STAT_COUNT = 7

DEAD_LEFT = 100
DEAD_TOP = 56
DEAD_WIDTH = 54
DEAD_HEIGHT = 16
DEAD_MSG_LEFT = 104
DEAD_MSG_TOP = 60

NO_MONSTER = $FF
NO_CRYSTAL = $FF

CRYSTAL_RED_TYPE = 0
CRYSTAL_BLUE_TYPE = 1
CRYSTAL_YELLOW_TYPE = 2

KEY_ENTER = 13